import { MISSIONS } from './data.js';
import { GameEngine } from './engine.js';

const canvas = document.querySelector('#game'), overlay = document.querySelector('#overlay');
let engine, activeMission = 0;
function button(label, fn) { const b=document.createElement('button');b.textContent=label;b.onclick=fn;return b; }
function card({eyebrow='',title,body='',fact='',actions=[]}) { overlay.innerHTML=''; const d=document.createElement('div');d.className='card';d.innerHTML=`${eyebrow?`<div class="eyebrow">${eyebrow}</div>`:''}<h1>${title}</h1>${body?`<p>${body}</p>`:''}${fact?`<div class="fact">${fact}</div>`:''}`; const a=document.createElement('div');a.className='choices';actions.forEach(([l,f])=>a.append(button(l,f)));d.append(a);overlay.append(d); }
function menu(){ card({eyebrow:'PLATAFORMA EDUCATIVA DE BIOLOGIA',title:'BIO<br>AVENTURA',body:'Uma jornada jogável pelo corpo humano. Corra, pule, aprenda e leve o oxigênio até as células.',actions:MISSIONS.map((m,i)=>[`${m.title} — ${m.subtitle}`,()=>intro(i)])}); }
function intro(i){activeMission=i;const m=MISSIONS[i];card({eyebrow:m.subtitle,title:m.title,body:m.introduction,fact:'Controles: A/D ou ←/→ para andar · Espaço, W ou ↑ para pular · ESC pausa · R reinicia.',actions:[['VAMOS LÁ!',()=>engine.start(m)]]});}
function state(s){const m=engine.mission;if(s==='playing'){overlay.innerHTML='';return;} if(s==='paused')card({eyebrow:'JOGO PAUSADO',title:'PAUSA',body:'Respire fundo. A aventura continua quando você quiser.',actions:[['CONTINUAR',()=>engine.pause()],['REINICIAR',()=>engine.restart()]]}); if(s==='levelComplete')card({eyebrow:'VOCÊ CHEGOU A',title:'FASE CONCLUÍDA!',body:engine.level.description,fact:`Aprendizado: ${engine.level.labels.map(l=>l.title).join(' · ')}.`,actions:[['PRÓXIMA FASE →',()=>engine.next()]]}); if(s==='missionComplete')card({eyebrow:'ETAPA CONCLUÍDA!',title:m.title,body:m.finalMessage,fact:m.finalFact,actions:[[m.nextMissionLabel,()=>activeMission+1<MISSIONS.length?intro(activeMission+1):menu()]]}); if(s==='gameOver')card({eyebrow:'AS BOLHAS ESCAPARAM',title:'TENTE DE NOVO',body:'Você pode reiniciar a fase e continuar aprendendo.',actions:[['RECOMEÇAR',()=>engine.restart()]]});}
engine=new GameEngine(canvas,state);menu();
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;for(const e of ['pointerdown','pointerenter'])b.addEventListener(e,ev=>{if(e==='pointerenter'&&!ev.buttons)return;engine.setKey(k,true);ev.preventDefault();});for(const e of ['pointerup','pointercancel','pointerleave'])b.addEventListener(e,()=>engine.setKey(k,false));});
